### ISSUE TITLE
Unusable without modification to package.json

### ISSUE THREAD

**Issue by davidsilverthorn-paradigm** [thomann061/fmrest#4]
For me, running Node 10.15.3 on Windows 10, I get a seemingly endless number of errors from fmrest until I modify package.json.

I had to update ` "main": "gulpfile.js",` to ` "main": "./lib/fmrest.js",` to prevent errors.

**Comment by beargie** [comment]
Not sure if @davidsilverthorn-paradigm is using [gulp](https://gulpjs.com/), but if so, then there's probably a different gulpfile.js setting that needs to be fixed in his install.

A sample vanilla node project running on node 10.8.0 for me has a package.json file that looks like this:
```
{
  "name": "fmNodeProject",
  "version": "1.0.0",
  "description": "Some Project Description",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "mbeargie",
  "license": "ISC",
  "dependencies": {
    "fmrest": "^2.2.1"
  }
}
```

There is no "main" tag in the standard JSON generated by `npm init` at all.

I can't duplicate the issue here with a standard installation of this package using `npm install fmrest`

**Comment by davidsilverthorn-paradigm** [comment]
What version of npm are you using? `Main` is certainly a standard tag. Even your example has it.

Furthermore, I had to modify the package.json file in fmrest, not my own project, to get it working.

**Comment by beargie** [comment]
Thanks for the clarification NPM 6.4.0 on my end.

**Comment by beargie** [comment]
I tested this further and it does appear that gulpfile.js is the correct pointer and is in the main directory:
https://github.com/thomann061/fmrest/blob/master/gulpfile.js

@thomann061 please update your release ASAP to account for this.

**Comment by thomann061** [comment]
Is this still an issue?

**Comment by belac9615** [comment]
@thomann061 Yes, this is still an issue.
